// Simple emoji-based icons to replace react-native-vector-icons
export const Icons = {
  upload: '📤',
  camera: '📷',
  image: '🖼️',
  home: '🏠',
  sun: '☀️',
  trash: '🗑️',
  clock: '⏰',
  award: '🏆',
  uploadCloud: '☁️',
  user: '👤',
  chevronRight: '›',
  bell: '🔔',
  helpCircle: '❓',
  logOut: '🚪',
  x: '✕',
  check: '✓',
  checkCircle: '✅',
  circle: '⭕',
  tag: '🏷️',
  arrowRight: '→',
  loader: '⏳',
};
